snmp_exporter_version: "0.26.0"
snmp_exporter_download_url: "https://github.com/prometheus/snmp_exporter/releases/download/v{{ snmp_exporter_version }}/snmp_exporter-{{ snmp_exporter_version }}.linux-amd64.tar.gz"
snmp_exporter_install_dir: "/usr/local/bin"
snmp_exporter_port: 9116
snmp_exporter_config: "/etc/snmp_exporter/snmp.yml"
