nvidia_dcgm_version: "3.3.9"
nvidia_dcgm_download_url: "https://github.com/NVIDIA/dcgm-exporter/releases/download/{{ nvidia_dcgm_version }}/dcgm-exporter-{{ nvidia_dcgm_version }}-linux-amd64.tar.gz"
nvidia_dcgm_install_dir: "/usr/local/bin"
nvidia_dcgm_port: 9400
